Explicit errors when MICROSCANNER_TOKEN is not set.

diff --git a/src/planet-4-151612/ubuntu/templates/Dockerfile.in b/src/planet-4-151612/ubuntu/templates/Dockerfile.in
--- a/src/planet-4-151612/ubuntu/templates/Dockerfile.in
+++ b/src/planet-4-151612/ubuntu/templates/Dockerfile.in
@@ -8,6 +8,8 @@ ARG MICROSCANNER_TOKEN
 
 ENV MICROSCANNER_TOKEN="${MICROSCANNER_TOKEN}"
 
+RUN if [ -z "${MICROSCANNER_TOKEN}" ]; then { echo "ERROR: MICROSCANNER_TOKEN not set"; exit 1; }; fi
+
 ADD https://get.aquasec.com/microscanner .
 
 RUN chmod 755 microscanner
@@ -25,7 +27,7 @@ RUN rm -fr /etc/apt/sources.list && \
     rm dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
     rm -fr /usr/share/man/* /usr/share/doc/*
 
-RUN ./microscanner "${MICROSCANNER_TOKEN}"
+RUN ./microscanner ${MICROSCANNER_TOKEN}
 
 FROM scratch
 
