Don't complain about missing MICROSCANNER_TOKEN if we're only templating

diff --git a/bin/inc/main b/bin/inc/main
--- a/bin/inc/main
+++ b/bin/inc/main
@@ -207,11 +207,13 @@ fi
 
 if [[ -z "${MICROSCANNER_TOKEN:-}" ]]
 then
-  echo "ERROR: Environment variable MICROSCANNER_TOKEN not set."
-  >&2 echo "ERROR: Environment variable MICROSCANNER_TOKEN not set."
-  >&2 echo "See: https://github.com/aquasecurity/microscanner#registering-for-a-token"
-  >&2 echo ""
-  exit 1
+  if [[ "${BUILD_LOCALLY}" = "true" ]] || [[ "${BUILD_REMOTELY}" = "true" ]]
+  then
+    >&2 echo "ERROR: Environment variable MICROSCANNER_TOKEN not set."
+    >&2 echo "See: https://github.com/aquasecurity/microscanner#registering-for-a-token"
+    >&2 echo ""
+    exit 1
+  fi
 fi
 
 BRANCH_NAME_RAW=${CIRCLE_BRANCH:-$(git rev-parse --abbrev-ref HEAD)}
