Use main single branch
- Fix scripts paths
- Remove git-flow logic and simplify promotion
- Update base contribution files
- add shfmt linting

diff --git a/bin/inc/main b/bin/inc/main
--- a/bin/inc/main
+++ b/bin/inc/main
@@ -20,16 +20,14 @@ BUILD_TMPDIR="$(mktemp -d "${TMPDIR:-/tmp/}$(basename 0).XXXXXXXXXXXX")"
 # Find real file path of current script
 # https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
 
-if [[ -z "${GIT_ROOT_DIR:-}" ]]
-then
+if [[ -z "${GIT_ROOT_DIR:-}" ]]; then
   source="${BASH_SOURCE[0]}"
-  while [[ -h "$source" ]]
-  do # resolve $source until the file is no longer a symlink
-    dir="$( cd -P "$( dirname "$source" )" && pwd )"
+  while [[ -L "$source" ]]; do # resolve $source until the file is no longer a symlink
+    dir="$(cd -P "$(dirname "$source")" && pwd)"
     source="$(readlink "$source")"
     [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
   done
-  GIT_ROOT_DIR="$( cd -P "$( dirname "$source" )/.." && pwd )"
+  GIT_ROOT_DIR="$(cd -P "$(dirname "$source")/.." && pwd)"
   export GIT_ROOT_DIR
 fi
 # ----------------------------------------------------------------------------
@@ -44,22 +42,22 @@ rm "${BUILD_TMPDIR}/pretty_print.sh"
 
 # VARIABLE ASSIGNMENT
 
-bash_version=$(bash --version | head -n 1| cut -d' ' -f4 | cut -d '.' -f 1)
+bash_version=$(bash --version | head -n 1 | cut -d' ' -f4 | cut -d '.' -f 1)
 
 env_parameters=()
 config_pass=0
 
 function contains() {
-    local n=$#
-    local value=${!n}
-    for ((i=1;i < $#;i++)) {
-        if [ "${!i}" == "${value}" ]; then
-            echo "y"
-            return 0
-        fi
-    }
-    echo "n"
-    return 1
+  local n=$#
+  local value=${!n}
+  for ((i = 1; i < $#; i++)); do
+    if [ "${!i}" == "${value}" ]; then
+      echo "y"
+      return 0
+    fi
+  done
+  echo "n"
+  return 1
 }
 
 # Reads key-value file as function argument, assigns variable to environment
@@ -67,8 +65,7 @@ function set_vars() {
   local file
   file="${1}"
   _build "Config pass #$config_pass"
-  while read -r line
-  do
+  while read -r line; do
     # Skip comments
     [[ $line == \#* ]] && continue
     # Skip lines that don't include an assignment =
@@ -80,28 +77,24 @@ function set_vars() {
 
     # Current value
     set +u
-    if [[ ${!key} ]]
-    then
+    if [[ ${!key} ]]; then
       current="${!key}"
     else
       current=
     fi
 
-    if [[ -z "$current" ]] || [[ $config_pass -gt 0 ]]
-    then
+    if [[ -z "$current" ]] || [[ $config_pass -gt 0 ]]; then
       # Skip any variables set in the environment
       #[[ $(contains "${env_parameters[@]}" $key) == "y" ]] && _build "[ENV] $key=${!key}" && continue
       # This key is not set yet
-      if [[ $bash_version -lt 4 ]]
-      then
+      if [[ $bash_version -lt 4 ]]; then
         # Urgh, eval is evil
         eval "${line}"
       else
         declare -g "$key=$value"
       fi
 
-      if [[ $value != "${current}" ]]
-      then
+      if [[ $value != "${current}" ]]; then
         _notice " ++ $key=$value"
       else
         _notice " -- $key=$value"
@@ -110,7 +103,7 @@ function set_vars() {
       _notice "[ENV] $key=${!key}"
       env_parameters+=($key)
     fi
-  done < "${file}"
+  done <"${file}"
   let config_pass+=1
   export config_pass
   printf "\n"
@@ -127,17 +120,15 @@ function set_vars() {
 # @todo prioritise ENV over config file ?
 
 default_config="${GIT_ROOT_DIR}/config.default"
-if [[ -f "${default_config}" ]]
-then
+if [[ -f "${default_config}" ]]; then
   set_vars "${default_config}"
 fi
-
 
 # ----------------------------------------------------------------------------
 
 # UTILITY
 
-function usage {
+function usage() {
   echo "Usage: $(basename "$0") [OPTION|OPTION2] [<image build list>|all]...
 Build and test artifacts in this repository
 
@@ -155,22 +146,27 @@ Options:
 # COMMAND LINE OPTIONS
 
 OPTIONS=':vc:lhpr'
-while getopts $OPTIONS option
-do
-    case $option in
-        c  )    # shellcheck disable=SC2034
-                CONFIG_FILE=$OPTARG;;
-        l  )    BUILD_LOCALLY=true;;
-        h  )    usage
-                exit 0;;
-        p  )    PULL_IMAGES=true;;
-        r  )    BUILD_REMOTELY=true;;
-        v  )    verbosity=debug
-                _verbose_debug on;;
-        *  )    echo "Unkown option: ${OPTARG}"
-                usage
-                exit 1;;
-    esac
+while getopts $OPTIONS option; do
+  case $option in
+    c) # shellcheck disable=SC2034
+      CONFIG_FILE=$OPTARG ;;
+    l) BUILD_LOCALLY=true ;;
+    h)
+      usage
+      exit 0
+      ;;
+    p) PULL_IMAGES=true ;;
+    r) BUILD_REMOTELY=true ;;
+    v)
+      verbosity=debug
+      _verbose_debug on
+      ;;
+    *)
+      echo "Unkown option: ${OPTARG}"
+      usage
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND - 1))
 
@@ -178,40 +174,33 @@ shift $((OPTIND - 1))
 
 # LOAD CUSTOM CONFIGURATION
 set +u
-if [[ ! -z "${CONFIG_FILE}" ]]
-then
+if [[ ! -z "${CONFIG_FILE}" ]]; then
   echo "Reading configuration from ${CONFIG_FILE}"
 
-  if [[ ! -f "${CONFIG_FILE}" ]]
-  then
+  if [[ ! -f "${CONFIG_FILE}" ]]; then
     _fatal "File not found: ${CONFIG_FILE}"
   fi
   # https://github.com/koalaman/shellcheck/wiki/SC1090
   set_vars "${CONFIG_FILE}"
 fi
 
-
 # ----------------------------------------------------------------------------
 # Configure build variables based on CircleCI environment vars
 
-if [[ "${CIRCLECI:-}" ]]
-then
+if [[ "${CIRCLECI:-}" ]]; then
   BUILD_NUM=${BUILD_NUM:-"build-${CIRCLE_BUILD_NUM}"}
 
-  if [[ -z "${BUILD_TAG:-}" ]]
-  then
+  if [[ -z "${BUILD_TAG:-}" ]]; then
     BUILD_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
   fi
 
 fi
 
-if [[ -z "${MICROSCANNER_TOKEN:-}" ]]
-then
-  if [[ "${BUILD_LOCALLY}" = "true" ]] || [[ "${BUILD_REMOTELY}" = "true" ]]
-  then
-    >&2 echo "ERROR: Environment variable MICROSCANNER_TOKEN not set."
-    >&2 echo "See: https://github.com/aquasecurity/microscanner#registering-for-a-token"
-    >&2 echo ""
+if [[ -z "${MICROSCANNER_TOKEN:-}" ]]; then
+  if [[ "${BUILD_LOCALLY}" = "true" ]] || [[ "${BUILD_REMOTELY}" = "true" ]]; then
+    echo >&2 "ERROR: Environment variable MICROSCANNER_TOKEN not set."
+    echo >&2 "See: https://github.com/aquasecurity/microscanner#registering-for-a-token"
+    echo >&2 ""
     exit 1
   fi
 fi
diff --git a/tests/_helpers b/tests/_helpers
--- a/tests/_helpers
+++ b/tests/_helpers
@@ -1,30 +1,30 @@
 #!/usr/bin/env bash
 set -ae
 
-function finish {
+function finish() {
   { set +ex; } 2>/dev/null
 }
 trap finish EXIT
 
-function warning {
-  >&2 echo "WARNING: $1"
+function warning() {
+  echo >&2 "WARNING: $1"
 }
 
-function error {
+function error() {
   fatal "$1"
 }
 
-function fatal {
-  >&2 echo "ERROR: $1"
+function fatal() {
+  echo >&2 "ERROR: $1"
   exit 1
 }
 
-function get_container_id {
+function get_container_id() {
   # Guesses correct container name, returns associated container ID
   docker ps --format '{{.Names}}' | grep "${BATS_IMAGE//[^[:alnum:]_]/}" | head -n1 | cut -d' ' -f1
 }
 
-function get_container_name {
+function get_container_name() {
   # Removes any non-alphanumeric or '_' characters,
   # in an attempt to match docker-compose service naming convention
   echo "${BATS_IMAGE//[^[:alnum:]_]/}_app_1"
@@ -32,21 +32,21 @@ function get_container_name {
 
 # Used in setup function to log file, line number and function information in
 # artifact storage for review and debug information
-function begin_output {
+function begin_output() {
   ARTIFACT_LOGS_DIR=${ARTIFACT_LOGS_DIR:-"/tmp/artifacts/logs"}
   [[ -d "$ARTIFACT_LOGS_DIR" ]] || mkdir -p "$ARTIFACT_LOGS_DIR"
   [[ -f "${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}" ]] || touch "${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
   PS4='+($(basename "$BASH_SOURCE"):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-  echo -e "=============== vvv [${BATS_TEST_NUMBER}] ${BATS_IMAGE} - ${BATS_TEST_DESCRIPTION}" >> "${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
+  echo -e "=============== vvv [${BATS_TEST_NUMBER}] ${BATS_IMAGE} - ${BATS_TEST_DESCRIPTION}" >>"${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
 }
 
 # Used in teardown function to store function output in artifacts
-function store_output {
+function store_output() {
   ARTIFACT_LOGS_DIR=${ARTIFACT_LOGS_DIR:-"/tmp/artifacts/logs"}
   # $output is defined in bats `run` command, don't panic @shellcheck
   # shellcheck disable=SC2154
-  echo "$output" >> "${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
-  echo -e "=============== ^^^ [${BATS_TEST_NUMBER}] ${BATS_IMAGE} - ${BATS_TEST_DESCRIPTION}\n" >> "${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
+  echo "$output" >>"${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
+  echo -e "=============== ^^^ [${BATS_TEST_NUMBER}] ${BATS_IMAGE} - ${BATS_TEST_DESCRIPTION}\n" >>"${ARTIFACT_LOGS_DIR}/${BATS_IMAGE}"
   PS4=''
 }
 
@@ -80,7 +80,7 @@ function simple_grep() {
 }
 
 # Queries an endpoint and expects a response to match regular expression parameter
-function curl_check_response_regex {
+function curl_check_response_regex() {
   set -euo pipefail
   trap finish EXIT
   local regex=${1:-"OK"}
@@ -89,12 +89,10 @@ function curl_check_response_regex {
 
   local interval=1
   local loop=${4:-60}
-  until docker run -t --network "container:${container}" --rm "${CURL_CONTAINER}" -s -k -N "${endpoint}" | grep -o "${regex}"
-  do
+  until docker run -t --network "container:${container}" --rm "${CURL_CONTAINER}" -s -k -N "${endpoint}" | grep -o "${regex}"; do
     sleep $interval
-    loop=$((loop-1))
-    if [[ $loop -lt 1 ]]
-    then
+    loop=$((loop - 1))
+    if [[ $loop -lt 1 ]]; then
       exit 1
     fi
   done
@@ -102,7 +100,7 @@ function curl_check_response_regex {
 
 # Queries an endpoint and expects a response status code to match parameter
 # shellcheck disable=SC2120
-function curl_check_status_code {
+function curl_check_status_code() {
   set -eu
   trap finish EXIT
   local status_code=${1:-200}
@@ -111,21 +109,18 @@ function curl_check_status_code {
 
   local interval=1
   local loop=${4:-60}
-  until docker run --network "container:${container}" --rm "${CURL_CONTAINER}" -s -k -o /dev/null -w "%{http_code}" "${endpoint}" | grep "${status_code}"
-  do
+  until docker run --network "container:${container}" --rm "${CURL_CONTAINER}" -s -k -o /dev/null -w "%{http_code}" "${endpoint}" | grep "${status_code}"; do
     sleep $interval
-    loop=$((loop-1))
-    if [[ $loop -lt 1 ]]
-    then
+    loop=$((loop - 1))
+    if [[ $loop -lt 1 ]]; then
       return 1
     fi
   done
 }
 
-
 # Queries an endpoint and expects a response status code to match parameter
 # shellcheck disable=SC2120
-function curl_get_response_header {
+function curl_get_response_header() {
   set -eu
   trap finish EXIT
   local var=${1:-status}
@@ -136,13 +131,13 @@ function curl_get_response_header {
 }
 
 # Pulls docker image parameter
-function pull_image {
+function pull_image() {
   set -eu
   trap finish EXIT
   docker pull "${1:-${image}}"
 }
 
-function start_docker_compose {
+function start_docker_compose() {
   set -eu
   trap finish EXIT
   # [[ -z "$1" ]] && fatal "Container name not set"
@@ -160,22 +155,20 @@ function start_docker_compose {
   docker-compose --no-ansi -p "${BATS_IMAGE//[^[:alnum:]_]/}" -f "${compose_file}" up --remove-orphans -d
 
   # Query the container until a 200 response is returned
-  until curl_check_status_code 200 "${endpoint}" "${container}"
-  do
+  until curl_check_status_code 200 "${endpoint}" "${container}"; do
     sleep $interval
-    loop=$((loop-1))
-    if [[ $loop -lt 1 ]]
-    then
+    loop=$((loop - 1))
+    if [[ $loop -lt 1 ]]; then
       docker-compose --no-ansi -p "${BATS_IMAGE//[^[:alnum:]_]/}" -f "$compose_file" stop
-      >&2 echo "Timeout without successful connection to ${endpoint} on ${container}"
-      >&2 docker-compose --no-ansi -p "${BATS_IMAGE//[^[:alnum:]_]/}" -f "$compose_file" logs
+      echo >&2 "Timeout without successful connection to ${endpoint} on ${container}"
+      docker-compose >&2 --no-ansi -p "${BATS_IMAGE//[^[:alnum:]_]/}" -f "$compose_file" logs
       exit 1
     fi
   done
   # Container is up and running
 }
 
-function clean_container {
+function clean_container() {
   set -eu
   trap finish EXIT
   [[ -z "$1" ]] && fatal "Container name not set"
@@ -184,7 +177,7 @@ function clean_container {
   yes | docker rm "$1" || true
 }
 
-function clean_docker_compose {
+function clean_docker_compose() {
   set -eu
   trap finish EXIT
   local compose_file="${1:-${BATS_TEST_DIRNAME}/../docker-compose.yml}"
@@ -192,7 +185,7 @@ function clean_docker_compose {
   docker-compose --no-ansi -p "${BATS_IMAGE//[^[:alnum:]_]/}" -f "${compose_file}" down -v
 }
 
-function run_test_image_exists {
+function run_test_image_exists() {
   set -eu
   trap finish EXIT
   [[ -z "$1" ]] && fatal "Expected response regex not set"
@@ -200,7 +193,7 @@ function run_test_image_exists {
   docker images | grep "${image_regex}"
 }
 
-function run_test_container_starts {
+function run_test_container_starts() {
   set -eu
   trap finish EXIT
   [[ -z "$1" ]] && fatal "No container name specified"
